git:
  commit: true
  commitMessage: "chore(release): ${version}"
  commitArgs: ""
  tag: true
  tagName: "v${version}"
  tagAnnotation: "Automated release: ${version}"
  push: true
  requireBranch: release
  requireCommits: true
  changelog: "npx auto-changelog --stdout --commit-limit false"

github:
  release: true
  releaseName: "v${version}"

npm:
  publish: false

plugins:
  "@release-it/conventional-changelog":
    infile: CHANGELOG.md
    preset:
      name: conventionalcommits
      types:
        - type: feat
          section: Features
        - type: fix
          section: Bug Fixes
        - tyep: docs
          section: Documentation
