#!/bin/bash

rm -rf *lua*.ipk *.deb
find . -name '*~' -delete

### Build AREDN package
export COPYFILE_DISABLE=1

# Main
rm -rf data.tar.gz control.tar.gz
cd src/data
tar cf ../../data.tar `find . -type f | grep -v DS_Store | grep -v .pl | grep -v .pm`
cd ../control
tar cfz ../../control.tar.gz .
cd ../..
gzip data.tar
COPYFILE_DISABLE=1 tar cfz meshchat_1.02-lua_all.ipk control.tar.gz data.tar.gz debian-binary

# API-only
rm -rf data.tar.gz control.tar.gz
cd apionly/data
tar cf ../../data.tar `find . -type f | grep -v DS_Store | grep -v .pl | grep -v .pm`
cd ../control
tar cfz ../../control.tar.gz .
cd ../..
gzip data.tar
COPYFILE_DISABLE=1 tar cfz meshchat-api_1.02-lua_all.ipk control.tar.gz data.tar.gz debian-binary

rm -rf data.tar.gz control.tar.gz *.deb
