#!/bin/bash

rm -rf *.ipk *.deb
find . -name '*~' -delete

### Build AREDN package
export COPYFILE_DISABLE=1
export VERSION=2.7

# Main
rm -rf data.tar.gz control.tar.gz
cd src/data
sed -i "s/^app_version.*$/app_version                = \"${VERSION}\"/" www/cgi-bin/meshchatconfig.lua
tar cf ../../data.tar `find . -type f | grep -v DS_Store | grep -v .pl | grep -v .pm`
cd ../control
sed -i "s/^Version: .*$/Version: ${VERSION}/" control
tar cfz ../../control.tar.gz .
cd ../..
gzip data.tar
COPYFILE_DISABLE=1 tar cfz meshchat_${VERSION}_all.ipk control.tar.gz data.tar.gz debian-binary

# API-only
rm -rf data.tar.gz control.tar.gz
cd apionly/data
tar cf ../../data.tar `find . -type f | grep -v DS_Store | grep -v .pl | grep -v .pm`
cd ../control
tar cfz ../../control.tar.gz .
cd ../..
gzip data.tar
COPYFILE_DISABLE=1 tar cfz meshchat-api_${VERSION}_all.ipk control.tar.gz data.tar.gz debian-binary

rm -rf data.tar.gz control.tar.gz *.deb
