#!/bin/sh

uci -c /etc/config.mesh show setup.services | grep "|8080|meshchat" &> /dev/null
PRESENT=$?

if [ "$PRESENT" != 0 ]; then
  RAND=$(awk 'BEGIN{srand();print int(rand()*10000) }')
  uci -c /etc/config.mesh add_list setup.services.service="MeshChat-$RAND [chat]|1|http|$(uname -n)|8080|meshchat"
  uci -c /etc/config.mesh commit setup
fi

/usr/local/bin/node-setup &> /dev/null
/usr/local/bin/restart-services.sh &> /dev/null

/etc/init.d/meshchatsync enable
/etc/init.d/meshchatsync start

exit 0
