#!/bin/sh

/etc/init.d/meshchatsync stop > /dev/null 2> /dev/null

mkdir -p /var/www/html/meshchat

# if there is not a meshchat_local.lua, then prepare one
if [ ! -f /usr/lib/cgi-bin/meshchat_local.lua ]; then
    if [ -f /usr/lib/cgi-bin/meshchatconfig.lua ]; then
        cp /usr/lib/cgi-bin/meshchatconfig.lua /usr/lib/cgi-bin/meshchat_local.lua

        # remove vars that should not be in meshchat_local.lua
        sed -i "/^protocol_version/d; /^app_version/d" /usr/lib/cgi-bin/meshchat_local.lua
    else
        touch /usr/lib/cgi-bin/meshchat_local.lua
    fi
fi

exit 0
