#!/bin/sh
if [ -d /www/meshchat/db ]
then
    if [ -f /www/meshchat/db/messages ]
    then
	     /bin/chmod 666 /www/meshchat/db/messages
    fi
    if [ -f /www/meshchat/db/messages_lock ]
    then
	     /bin/chmod 666 /www/meshchat/db/messages_lock
    fi

     /bin/chown -R root:root /www/cgi-bin
     /bin/chown -R root:root /www/meshchat

    /etc/init.d/meshchatsync enable
    #killall meshchatsync
    /etc/init.d/meshchatsync start
fi

grep "|8080|meshchat" /etc/config.mesh/_setup.services.dmz &> /dev/null
DMZPRESENT=$?
grep "|8080|meshchat" /etc/config.mesh/_setup.services.nat &> /dev/null
NATPRESENT=$?
NODEMODE=$(uci -q -c /etc/local/uci/ get hsmmmesh.settings.config)
RAND=$(awk 'BEGIN{srand();print int(rand()*10000) }')

if [ "$DMZPRESENT" != 0 ]; then
  echo "MeshChat-$RAND|1|http|$(uname -n)|8080|meshchat" >> /etc/config.mesh/_setup.services.dmz
fi

if [ "$NATPRESENT" != 0 ]; then
  echo "MeshChat-$RAND|1|http|$(uname -n)|8080|meshchat" >> /etc/config.mesh/_setup.services.nat
fi

if [ "$NODEMODE" = "mesh" ]; then
  echo "Applying service announcement"
  /usr/local/bin/node-setup -a -p mesh &> /dev/null
  /etc/init.d/olsrd restart &> /dev/null
  echo "<br>"
fi

echo "Mesh Chat has been setup at http://$(uname -n):8080/meshchat"
echo "<br>"
echo "An advertised service has been added for Mesh Chat on the Services configuration page"

exit 0
