name: Bug Report
description: File a bug for the MeshChat project
title: "[Bug]: "
labels:
  - bug
  - needs triage
assignees:
  - hickey
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to create a bug report. Please
        attempt to fill in as much information as you are able to.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Version of MeshChat?
      options:
        - v1.x
        - v2.0 - v2.8
        - v2.9
        - v2.10
        - v2.12.0
        - development build (include version in what happened)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: system_type
    attributes:
      label: System Type
      description: What type of system is MeshChat installed on?
      options:
        - AREDN node
        - Linux
        - Unknown
      default: 0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: |
        Describe to the best of your ability what happened or what you
        did to trigger the problem.
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: MeshChat configuration
      description: |
        If you are the admin of the MeshChat instance, it is asked that
        you past your MeshChat configuration file between the back ticks
        to aid in troubleshooting.
      value: |
        ```
        <Insert config file here>
        ```
  - type: dropdown
    id: connection_type
    attributes:
      label: Connection type
      multiple: false
      description: |
        How is the node that is running the MeshChat instance connected?
        If you know the mesh network that the node is connected to please
        indicate the name of the mesh network below in the node name field.
      options:
        - Non-connected mesh network
        - Mesh network connected through IP tunnel
        - Mesh network connected through a supernode
        - I don't know
  - type: input
    id: node_name
    attributes:
      label: Node name
      description: Please specify the node name where MeshChat runs.
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Brave
        - Vivialdi
        - Other
