#!/usr/bin/lua

require('luci.sys')
require('luci.http')

local query = {}
if os.getenv("QUERY_STRING") ~= "" then
    query = luci.http.Request(luci.sys.getenv()):formvalue()
end

print("Content-type: text/plain\r")
print("\r")
if query.action == "meshchat_nodes" then
    local pattern = "http://(%S+):(%d+)/meshchat|tcp|" .. query.zone_name:gsub("-", "%%-") .. "%s"
    for line in io.lines("/var/run/services_olsr")
    do
        local node, port = line:match(pattern)
        if node and port then
            print(node .. "\t" .. port)
        end
    end
else
    print("error no action")
end
