#!/usr/bin/lua

require('luci.sys')
require('luci.http')

local query = {}
if os.getenv("QUERY_STRING") ~= "" or os.getenv("REQUEST_METHOD") == "POST" then
    local request = luci.http.Request(luci.sys.getenv(),
        function()
            local v = io.read(1024)
            if not v then
                io.close()
            end
            return v
        end
    )
    local fp
    query = request:formvalue()
end

if query.action == "meshchat_nodes" then
    print("Content-type: text/plain\r")
    print("\r")

    local pattern = "http://(%S+):(%d+)/meshchat|tcp|" .. query.zone_name:gsub("-", "%%-") .. "%s"
    for line in io.lines("/var/run/services_olsr")
    do
        local node, port = line:match(pattern)
        if node and port then
            print(node .. "\t" .. port)
        end
    end
else
    print("Content-type: text/plain\r")
    print("\r")
    print("error no action")
end
