name: Build MeshChat Package
on:
  workflow_call:
    inputs:
      build_version:
        required: true
        type: string
      build_dir:
        required: true
        type: string
      ref:
        required: false
        type: string
        default: ${{ github.ref_name }}

jobs:
  create-meshchat-debian-package:
    runs-on: ubuntu-latest
    # container:
    #   image: registry.gitlab.com/wt0f/gitlab-runner-images/shell:latest
    outputs:
      package_file: ${{ steps.detect-package-file.outputs.file }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}
      # - run: info "Populating the filesystem with MeshChat files"
      - run: echo ${{ inputs.build_version }} > VERSION
      - run: package/populate-meshchat-fs.sh ${{ inputs.build_dir }} debian
      # - run: info "Updating version numbers to "
      - run: package/update-version.sh ${{ inputs.build_dir }}
      # - run: info "Packing up MeshChat files"
      - run: dpkg-deb --root-owner-group --build ${{ inputs.build_dir }}
      - run: mv package/meshchat-deb.deb meshchat_${{ inputs.build_version }}_all.deb
      - id: detect-package-file
        run: echo "file=meshchat_${{inputs.build_version }}_all.deb" >> $GITHUB_OUTPUT
      - run: echo "${{ steps.detect-package-file.outputs.file }}"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.detect-package-file.outputs.file }}
          path: ${{ steps.detect-package-file.outputs.file }}
