name: Build MeshChat Package
on:
  workflow_call:
    inputs:
      build_version:
        required: true
        type: string
      build_dir:
        required: true
        type: string
      ref:
        required: false
        type: string
        default: ${{ github.ref_name }}

jobs:
  create-meshchat-package:
    runs-on: ubuntu-latest
    # container:
    #   image: registry.gitlab.com/wt0f/gitlab-runner-images/shell:latest
    outputs:
      package_file: ${{ steps.detect-package-file.outputs.file }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}
      # - run: info "Populating the filesystem with MeshChat files"
      - run: echo ${{ inputs.build_version }} > VERSION
      - run: package/populate-meshchat-fs.sh ${{ inputs.build_dir }}
      # - run: info "Updating version numbers to "
      - run: package/update-version.sh ${{ inputs.build_dir }}
      # - run: info "Packing up MeshChat files"
      - run: package/ipk-build.sh ${{ inputs.build_dir }}
      - id: detect-package-file
        run: echo "file=$(ls -1 meshchat_*.ipk)" >> $GITHUB_OUTPUT
      - run: echo "${{ steps.detect-package-file.outputs.file }}"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.detect-package-file.outputs.file }}
          path: ${{ steps.detect-package-file.outputs.file }}
